er_email="yaswanthmitta@gmail.com"
key_file="$HOME/.ssh/id_ed25519"
echo "🔑 Starting SSH key generation process..."
echo "➡️ Generating new SSH key for: $user_email"
ssh-keygen -t ed25519 -C "$user_email" -f "$key_file" -N ""
echo "✅ SSH key generated successfully!"
eval "$(ssh-agent -s)"
echo "➡️ Adding SSH key to the ssh-agent..."
ssh-add "$key_file"
echo "✅ SSH key added to the agent."
echo "--------------------------------------------------------"
echo "➡️ Your public SSH key is below. Copy this entire block and add it to your GitHub account settings."
echo "--------------------------------------------------------"
cat "$key_file.pub"
echo "--------------------------------------------------------"
echo "✅ Public key displayed. You can also find it at: $key_file.pub"
echo "--------------------------------------------------------"
