name: Publish Docker Images to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: "yaswanthmitta" # Replace with your Docker Hub username or organization

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set image tag using GITHUB_SHA
        id: set_image_tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/multiapp-frontend:latest
            ${{ env.DOCKER_REPO }}/multiapp-frontend:${{ steps.set_image_tag.outputs.IMAGE_TAG }}

      - name: Build and push user-management-go image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/user-management-go
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/multiapp-user-management-go:latest
            ${{ env.DOCKER_REPO }}/multiapp-user-management-go:${{ steps.set_image_tag.outputs.IMAGE_TAG }}

      - name: Build and push todo-app image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/todo-app
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/multiapp-todo-app:latest
            ${{ env.DOCKER_REPO }}/multiapp-todo-app:${{ steps.set_image_tag.outputs.IMAGE_TAG }}

      - name: Build and push notes-app image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/notes-app
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/multiapp-notes-app:latest
            ${{ env.DOCKER_REPO }}/multiapp-notes-app:${{ steps.set_image_tag.outputs.IMAGE_TAG }}

      - name: Build and push bedrock-app image
        uses: docker/build-push-action@v5
        with:
          context: ./bedrock-app
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/multiapp-bedrock-app:latest
            ${{ env.DOCKER_REPO }}/multiapp-bedrock-app:${{ steps.set_image_tag.outputs.IMAGE_TAG }}
